config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  root to: 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  INTERST_COMPOUNDED_PER_YEAR = 12

  belongs_to :user

  validates :name, presence: true
  validates :unit_price_cents, presence: true, numericality: true
  validates :interest, presence: true, numericality: true
  validates :duration, presence: true, numericality: true

  monetize :unit_price_cents

  def year_value(year)
    (
    unit_price_dollars *
        (1 + interest / 100 / INTERST_COMPOUNDED_PER_YEAR)**(INTERST_COMPOUNDED_PER_YEAR * year)
  ).round(2)
  end

  def unit_price_dollars
    unit_price_cents / 100
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable, :validatable

  has_many :stocks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_out_path_for(_arg)
    root_path
  end

  def after_sign_in_path_for(_arg)
    stocks_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index; end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: %i[show edit update destroy]

  def index
    # add will_paginate/caminari

    @stocks = []
    @stocks = current_user.stocks.page(params[:page]).per(2)
  end

  def show
    @chart_data = (0..@stock.duration).inject({}) do |result, year|
      result.merge(year => @stock.year_value(year))
    end
  end

  def new
    @stock = Stock.new
  end

  def edit; end

  def create
    @stock = current_user.stocks.new(stock_params)
    if @stock.save
      redirect_to @stock, notice: 'Stock was successfully created.'
    else
      render :new
    end
  end

  def update
    if @stock.update(stock_params)
      redirect_to @stock, notice: 'Stock was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @stock.destroy
      redirect_to stocks_url, notice: 'Stock was successfully destroyed.'
    else
      redirect_to stocks_url, alert: 'Can\'t destroy the stock.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = current_user.stocks.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to stocks_url, alert: 'Couldn\'t find the Stock'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stock_params
    params.require(:stock).permit(:name, :unit_price, :unit_price_cents, :interest, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
        concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/landing/index.html.erb
<div class="text-center">
  <h1>Stock productivity calculator</h1>
  <%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-primary" %>
  or <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-secondary" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar justify-content-between">
  <div class="btn-group">
    <%= link_to 'Stocks', stocks_path, class: "navbar-brand" %>
    <%= link_to 'Add Stock', new_stock_path, class: "navbar-brand" if user_signed_in? %>
  </div>
  <% if user_signed_in? %>
    <div class="btn-group">
      <button class="btn btn-outline-primary dropdown-toggle"
              data-toggle="dropdown">
        <%= current_user.email %>
      </button>
      <div class="dropdown-menu">
        <%= link_to 'Your profile', edit_user_registration_path, method: :get, class: "dropdown-item" %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock productivity calculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container h-100">
      <%= render 'layouts/navbar' %>
      <%= flash_messages %>

      <div class="h-100 justify-content-center align-items-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<div class="row h-100 justify-content-center align-items-center">
  <%= form_with(model: stock, local: true) do |form| %>
    <div class="field form-group">
      <%= form.label :name %>
      <%= form.text_field :name, required: true, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :unit_price %>
      <%= form.number_field :unit_price, required: true, max: 21474836.47, step: 0.01, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label 'Interest in percents' %>
      <%= form.number_field  :interest, required: true, max: 100 , step: 0.1, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label 'Duration in years' %>
      <%= form.number_field :duration, required: true, max: 100 , class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/stocks/edit.html.erb
<h1 class="text-center">Editing Stock</h1>

<%= render 'form', stock: @stock %>

app/views/stocks/index.html.erb
<% if current_user %>

  <h1>Stocks</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Unit price</th>
      <th scope="col">Interest</th>
      <th scope="col">Duration</th>
    </tr>
    </thead>

    <tbody>
    <% if @stocks.size > 0 %>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= link_to stock.name, stock %></td>
          <td><%= humanized_money_with_symbol stock.unit_price %></td>
          <td><%= stock.interest %></td>
          <td><%= stock.duration %></td>
        </tr>
      <% end %>
    <% else %>
    <tr>
      <td colspan="4">
        No data
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @stocks, theme: 'twitter-bootstrap-4',
               pagination_class: "pagination-sm" %>

  <br>
<% else %>
<% end %>

app/views/stocks/new.html.erb
<h1 class="text-center">New Stock</h1>
<div>
  <%= render 'form', stock: @stock %>
</div>

app/views/stocks/show.html.erb
<p class="lead">
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p class="lead">
  <strong>Unit price:</strong>
  <%= humanized_money_with_symbol @stock.unit_price %>
</p>

<p class="lead">
  <strong>Interest:</strong>
  <%= @stock.interest %>
</p>

<p class="lead">
  <strong>Duration, years:</strong>
  <%= @stock.duration %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock), class: "btn btn-outline-primary btn-sm" %>

<%= bar_chart(@chart_data, ytitle: "Year", xtitle: "Amount, dollars") %>